blank_issues_enabled: false
contact_links:
  - name: Want to discuss anything else?
    url: https://github.com/WasiqB/ultra-reporter-app/discussions/new
    about: Create a discussion about it.
  - name: You can also join our Discord server
    url: https://dub.sh/lta-community
    about: Join our Discord server.
